### ISSUE TITLE
Consolidate `repo` / `owner` inputs to match ${{ github.repository }} output

### ISSUE THREAD

**Issue by OscarVanL** [lasith-kg/dispatch-workflow#163]
I'd like to use this action to call a workflow dispatch on the _same_ repo I'm currently on.

I'd like to get the repo name and owner dynamically, like this:
```
        uses: lasith-kg/dispatch-workflow@v1
        id: workflow-dispatch
        with:
          dispatch-method: 'workflow_dispatch'
          repo: ${{ github.repository }}
          owner: ${{ github.repository_owner }}
```

However, regrettably, `${{ github.repository }}` evaluates to `$OWNER/$REPO`. There doesn't appear to be a way to just get the repo's name and not the owner dynamically like this.

If there was an arg `repository` that takes `${{ github.repository}}` this would make my life a lot easier, as currently to use this action I need a way to split the value of the `${{ github.repository }}` on `/` and take only the second part.

Really, this feature request is only necessary because of (another) deficiency of the GitHub Actions functionality, but we know what getting features out of GitHub Actions is like (like getting blood out of a stone 😓)...

Thank you for creating this workflow and helping paper around these many deficiencies 👏
