### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading 'WorkflowDispatch')`

### ISSUE THREAD

**Issue by DanielAtanasovski** [lasith-kg/dispatch-workflow#66]
Using the latest version(1.6.1), received the following error in the logs of the action:
```
##[debug]TypeError: Cannot read properties of undefined (reading 'WorkflowDispatch')
##[debug]    at /home/ubuntu/actions-runner/_work/_actions/lasith-kg/dispatch-workflow/v1/webpack:/dispatch-workflow/lib/index.js:62:1
##[debug]    at Generator.next (<anonymous>)
##[debug]    at fulfilled (/home/ubuntu/actions-runner/_work/_actions/lasith-kg/dispatch-workflow/v1/webpack:/dispatch-workflow/lib/index.js:28:1)
##[debug]    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Triggering Action:
```YAML
      - id: deploy-app
        uses: lasith-kg/dispatch-workflow@v1
        name: 'Dispatch Workflow using workflow_dispatch Method'
        with:
          dispatch-method: workflow_dispatch
          repo: app-repo
          owner: ${{ github.repository_owner }}
          ref: refs/heads/main # or main
          workflow: deploy-or-delete.yml # Or Workflow ID
          token: ${{ steps.repo-token.outputs.github_token }}
          discover: true
          workflow-inputs: |
            {
              "namespace": "${{ inputs.environment }}",
              "version": "${{ steps.find-version.outputs.VERSION }}",
              "command": "deploy"
            }
```

Receiving Workflow:
```YAML
---
name: Deploy / Remove from Environment
run-name: >
  Deploy or Delete [${{
    inputs.distinct_id && inputs.distinct_id || 'N/A' }}]

on:  # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [org-k8s-deploy]
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Namespace to deploy to'
        required: true
        type: string
      version:
        description: 'Version to deploy (required for deployments)'
        required: false
        type: string
      command:
        description: 'Deploy command'
        required: true
        type: choice
        default: 'deploy'
        options:
          - 'deploy'
          - 'delete'
      distinct_id:
        description: 'A unique ID provided when dispatching this workflow (cross repo dispatch)'
        required: false
        type: string

env:
  APPLICATION: 'app'
  TIMEOUT: '120'  # This is application specific! Customise the default to your application

jobs:
  deploy:
    name: Deploy / Delete
    runs-on: [self-hosted, Linux]
    permissions:
      id-token: write
      contents: read
      deployments: write
    steps:
      - name: deploy action
        uses: internal-org/deploy-action/minimal@v2
        with:
          application: "${{ env.APPLICATION }}"
          timeout: "${{ env.TIMEOUT }}"
          data: '{ "github": ${{ toJSON(github) }}, "secrets": ${{ toJSON(secrets) }} }'

  annotate:
    # Helpful annotation on the workflow to tell you _who_ dispatched this workflow
    if: ${{ github.event_name == 'repository_dispatch' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: "${{ github.event.client_payload.dispatched_by }}"
        uses: reecetech/dispatch-annotation-action@v0

```

Last known working version was ('lasith-kg/dispatch-workflow@v1' (SHA:a5dbb1b2ba9016fd96bb66355067bf50d4c96c29))
